name: 'Copy file (with spaces)'
description: 'Copy local files'
author: 'Ricardo Canastro'
inputs:
  flags:
    description: 'Flags to use on the cp command. See "man cp" or "cp --help" for more details'
    required: false
    default: ''
  source:
    description: 'Source file'
    required: true
  target:
    description: 'Target file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{inputs.flags}}
    - ${{inputs.source}}
    - ${{inputs.target}}
branding:
  icon: 'copy'
  color: 'green'